version: "3.8"

services:
  service_a:
    build:
      context: .
      dockerfile: cmd/service_a/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SERVICE_B_URL=http://weather:8080

  weather:
    build:
      context: .
      dockerfile: cmd/weather/Dockerfile
    ports:
      - "8080:8080"
